apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: dra-perf
featureGates:
  DynamicResourceAllocation: true
runtimeConfig:
  "resource.k8s.io/v1beta1": "true"
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
            max-requests-inflight: "800"
            max-mutating-requests-inflight: "400"
        etcd:
          local:
            extraArgs:
              quota-backend-bytes: "8589934592"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            max-pods: "600"
